model:
  hidden_size: 256
decoder:
  max_length: 20
  embedding_size: 256
train:
  learning_rate: 0.001
  print_every: 100
  plot_every: 100
  n_epochs: 1
dataset:
  root_dir: flickr30k_images
  caption_file: results.csv
  image_folder: 'flickr30k_images'
  max_length: 20
dataloader:
  batch_size: 64
  shuffle: True