model:
  hidden_size: 512
decoder:
  # hidden_size: 768
  # encoder_dim: 512
  num_heads: 8
  num_layers: 6
  dropout_p: 0.2
encoder:
  model_name: vit_base_patch16_224
train:
  encoder_learning_rate: 0.0001
  decoder_learning_rate: 0.0001
  print_every: 1
  plot_every: 1
  n_epochs: 100
  teacher_forcing_ratio: 0.2
  early_stopping: 20
dataset:
  root_dir_local: /Users/youssefshaarawy/Documents/Datasets/INM706/flickr30k_images
  root_dir: flickr30k_images
  caption_file: results.csv
  image_folder: flickr30k_images
  max_length: 20
dataloader:
  batch_size: 32
  shuffle: True
  pin_memory: True